import { ThemeConfig, ThemeId } from '../types';

export const THEMES: ThemeConfig[] = [
  {
    id: 'dark-default',
    name: 'Escuro Padrão',
    tagline: 'Grafite & Ardósia Neutro',
    category: 'dark',
    primaryHex: '#6366f1',
    bgHex: '#0b0f19',
    cardHex: '#111827',
    borderHex: '#1e293b',
    glowHex: 'rgba(99, 102, 241, 0.25)',
    description: 'Tema escuro equilibrado com base ardósia, excelente contraste visual e acentos índigo sutis.',
  },
  {
    id: 'dark-purple',
    name: 'Escuro & Roxo',
    tagline: 'Violeta Neon & Obsidiana',
    category: 'dark',
    primaryHex: '#a855f7',
    bgHex: '#0b0716',
    cardHex: '#140e26',
    borderHex: '#2c1d52',
    glowHex: 'rgba(168, 85, 247, 0.3)',
    description: 'Ambiente noturno com aura púrpura profunda, acentos violeta elétrico e brilho futurista.',
  },
  {
    id: 'dark-blue',
    name: 'Escuro & Azul',
    tagline: 'Oceano Profundo & Ciano Tech',
    category: 'dark',
    primaryHex: '#0ea5e9',
    bgHex: '#030c18',
    cardHex: '#0a182b',
    borderHex: '#143258',
    glowHex: 'rgba(14, 165, 233, 0.3)',
    description: 'Estética cyber de alta densidade com base marinho profundo e acentos em ciano elétrico.',
  },
  {
    id: 'dark-emerald',
    name: 'Escuro & Esmeralda',
    tagline: 'Cyber Matrix & Menta',
    category: 'dark',
    primaryHex: '#10b981',
    bgHex: '#030f0a',
    cardHex: '#091f15',
    borderHex: '#15422e',
    glowHex: 'rgba(16, 185, 129, 0.3)',
    description: 'Estilo fintech e terminal com fundo verde musgo escuro e realces vibrantes em menta.',
  },
  {
    id: 'dark-amber',
    name: 'Escuro & Âmbar',
    tagline: 'Crepúsculo & Ouro Solar',
    category: 'dark',
    primaryHex: '#f59e0b',
    bgHex: '#0d0a06',
    cardHex: '#18130c',
    borderHex: '#352a1c',
    glowHex: 'rgba(245, 158, 11, 0.3)',
    description: 'Paleta quente e relaxante para leitura noturna, base obsidiana e acentos âmbar dourado.',
  },
  {
    id: 'dark-oled',
    name: 'Escuro OLED Puro',
    tagline: 'Preto Absoluto & Titânio',
    category: 'dark',
    primaryHex: '#f5f5f5',
    bgHex: '#000000',
    cardHex: '#0a0a0a',
    borderHex: '#1f1f1f',
    glowHex: 'rgba(255, 255, 255, 0.2)',
    description: 'Preto 100% puro para máxima eficiência em telas OLED, contraste infinito e acabamento titânio.',
  },
  {
    id: 'light-clean',
    name: 'Claro Minimalista',
    tagline: 'Clean White & Índigo',
    category: 'light',
    primaryHex: '#4f46e5',
    bgHex: '#f8fafc',
    cardHex: '#ffffff',
    borderHex: '#e2e8f0',
    glowHex: 'rgba(79, 70, 229, 0.15)',
    description: 'Tema diurno clássico e arejado com canvas claro e tipografia de alta legibilidade.',
  },
];

export const DEFAULT_THEME: ThemeId = 'dark-default';

export function getThemeConfig(id: ThemeId): ThemeConfig {
  return THEMES.find((t) => t.id === id) || THEMES[0];
}
